Models/Laptop.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Lab3_CNPM.Models
{
    public class Laptop
    {
        public Laptop()
        {

        }

        public Laptop(string id, string name, int price, string cpu, int ram, int storage)
        {
            ID = id;
            Name = name;
            Price = price;
            CPU = cpu;
            RAM = ram;
            Storage = storage;
        }

        public string ID { get; set; }
        [Required]
        [MaxLength(128)]
        public string Name { get; set; }
        [Required]
        public int Price { get; set; }
        public string CPU { get; set; }
        public int RAM { get; set; }
        public int Storage { get; set; }

    }
}

Models/LaptopDAO.cs
using Lab3_CNPM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab3_CNPM
{
    public class LaptopDAO
    {
        private LaptopContext db;
        public LaptopDAO(LaptopContext context)
        {
            this.db = context;
        }

        public IEnumerable<Laptop> GetAll()
        {
            return db.Laptops;
        }

        public bool AddLaptop(Laptop lap)
        {
            try
            {
                db.Laptops.Add(lap);
                db.SaveChanges();
                return true;
            }
            catch
            {
                return false;
            }
        }

        // assume that the 'lap' object is previously retrived from database via LaptopContext
        public bool UpdateLaptop(Laptop lap)
        {
            try
            {
                db.Entry(lap).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return true;
            }
            catch
            {
                return false;
            }
        }

        public bool DeleteLaptop(Laptop lap)
        {
            try
            {
                db.Laptops.Remove(lap);
                db.SaveChanges();
                return true;
            }
            catch
            {
                return false;
            }
        }

        public IEnumerable<Laptop> GetAllLaptops()
        {
            return db.Laptops; // this is lazy loading. The data is only loaded when we loop over it
        }

        // get all laptops by cpu name
        public List<Laptop> GetLaptopByCPU(String cpu)
        {
            return db.Laptops.Where(laptop => laptop.CPU == cpu).ToList<Laptop>();
        }

        public IEnumerable<Laptop> GetLaptopHasRamEqualOrGreaterThan(int ram)
        {
            var data = from laptop in db.Laptops
                       where laptop.RAM >= ram
                       select laptop;

            return data;
        }

        public int GetLaptopCount()
        {
            return (from lap in db.Laptops
                    select lap).Count();
        }

        public Laptop GetLaptop(string id)
        {
            return db.Laptops.Find(id);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab3_CNPM.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/LaptopsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab3_CNPM;
using Lab3_CNPM.Models;

namespace Lab3_CNPM.Controllers
{
    public class LaptopsController : Controller
    {
        private LaptopDAO dao = new LaptopDAO(new LaptopContext());

        // GET: Laptops
        public ActionResult Index()
        {
            return View(dao.GetAll());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Laptop model)
        {
            dao.AddLaptop(model);
            return RedirectToAction("Index");
        }

        public ActionResult CreateLaptop()
        {
            if (dao.GetLaptopCount() > 0)
            {
                return RedirectToAction("Index");
            }
            dao.AddLaptop(new Laptop("L001", "Macbook Air", 999, "i5", 8, 128));
            dao.AddLaptop(new Laptop("L002", "Macbook Air", 1299, "i5", 8, 256));
            dao.AddLaptop(new Laptop("L003", "Macbook Air", 1499, "i7", 16, 512));
            dao.AddLaptop(new Laptop("L004", "Macbook Pro 13\"", 1299, "i5", 8, 256));
            dao.AddLaptop(new Laptop("L005", "Macbook Pro 13\"", 1699, "i5", 8, 512));
            dao.AddLaptop(new Laptop("L006", "Macbook Pro 13\"", 1899, "i7", 16, 256));
            dao.AddLaptop(new Laptop("L007", "Macbook Pro 13\"", 2199, "i7", 16, 512));
            dao.AddLaptop(new Laptop("L008", "Macbook Pro 15\"", 2199, "i5", 16, 256));
            dao.AddLaptop(new Laptop("L009", "Macbook Pro 15\"", 2399, "i5", 16, 512));
            dao.AddLaptop(new Laptop("L0010", "Macbook Pro 15\"", 2499, "i7", 16, 512));
            dao.AddLaptop(new Laptop("L011", "Macbook Pro 15\"", 2699, "i7", 32, 1024));

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dao.DeleteLaptop(dao.GetLaptop(id));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Laptop laptop = dao.GetLaptop(id);
            return View("Update", laptop);
        }

        [HttpPost]
        public ActionResult Update(Laptop laptop)
        {
            if (ModelState.IsValid)
            {
                dao.UpdateLaptop(laptop);
                return RedirectToAction("Index");
            }
            return View(laptop);
        }

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Laptops/Create.cshtml
@model Lab3_CNPM.Models.Laptop
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create new Laptop</h1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Laptop</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPU, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RAM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RAM, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Storage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Storage, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Laptops/Index.cshtml
@model IEnumerable<Lab3_CNPM.Models.Laptop>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h2>Laptop List</h2>
    <button class="btn btn-info" onclick="location.href='@Url.Action("Create", "Laptops")'">Create</button>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(lap => lap.ID)</th>
                <th>@Html.DisplayNameFor(lap => lap.Name)</th>
                <th>@Html.DisplayNameFor(lap => lap.CPU)</th>
                <th>@Html.DisplayNameFor(lap => lap.RAM)</th>
                <th>@Html.DisplayNameFor(lap => lap.Storage)</th>
                <th>@Html.DisplayNameFor(lap => lap.Price)</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var lap in Model)
                {
                    <tr>
                        <td>@lap.ID</td>
                        <td>@lap.Name</td>
                        <td>Core @lap.CPU</td>
                        <td>@lap.RAM GB</td>
                        <td>@lap.Storage GB</td>
                        <td>@String.Format("{0:n0}", lap.Price) USD</td>
                        <td>
                            @Html.ActionLink("Edit", "Update", new { @id = lap.ID }) | @Html.ActionLink("Delete", "Delete", new { @id = lap.ID })
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>

Views/Laptops/Update.cshtml
@model Lab3_CNPM.Models.Laptop
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
<h2>Edit</h2>
@using (Html.BeginForm("Update", "Laptops", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Laptop</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPU, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RAM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RAM, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Storage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Storage, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Hieu Le App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" asp-controller="Latops" asp-action="Index">Laptop Shop App</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="container">
                &copy; 2020 - Movie App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>